# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.photoArea = QtWidgets.QScrollArea(self.centralwidget)
        self.photoArea.setWidgetResizable(True)
        self.photoArea.setObjectName("photoArea")
        self.photoAreaWidgetContents = QtWidgets.QWidget()
        self.photoAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1580, 751))
        self.photoAreaWidgetContents.setObjectName("photoAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.photoAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_image = QtWidgets.QLabel(self.photoAreaWidgetContents)
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.gridLayout_2.addWidget(self.label_image, 0, 0, 1, 1)
        self.verticalWidget = QtWidgets.QWidget(self.photoAreaWidgetContents)
        self.verticalWidget.setMinimumSize(QtCore.QSize(150, 50))
        self.verticalWidget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalWidget)
        self.textBrowser.setMinimumSize(QtCore.QSize(150, 50))
        self.textBrowser.setMaximumSize(QtCore.QSize(500, 50))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.tableView = QtWidgets.QTableView(self.verticalWidget)
        self.tableView.setMinimumSize(QtCore.QSize(150, 0))
        self.tableView.setMaximumSize(QtCore.QSize(500, 16777215))
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.gridLayout_2.addWidget(self.verticalWidget, 0, 1, 1, 1)
        self.photoArea.setWidget(self.photoAreaWidgetContents)
        self.gridLayout.addWidget(self.photoArea, 0, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Open"))
